### model
model_name_or_path: ../saves/qwen2vl_7b_full_sft_text_only/full/sft_epoch2_lr5e-6_warm003

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: mulberry_54k_interleave_ra
template: qwen2_vl
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../saves/qwen2vl_7b_full_sft_interleaved/full/sft_epoch6_lr1e-6_warm01 
logging_steps: 10
save_steps: 9999
save_only_model: true
save_strategy: 'epoch'
plot_loss: true
overwrite_output_dir: true
# max_steps: 3

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-6
num_train_epochs: 6
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 1